- wp-config.php
Load the WordPress API early, so autoloaded files can make use of add action etc.
> Load plugin API early

- wp-config.php
> Coding standards fix

- inc/namespace.php
> Disable the file editor

- docs/README.md
- docs/branding.md
I've left out the stuff about toggling platform branding in the meantime, not sure we want to show that.
Fixes #33
> Add docs stub

- inc/branding/namespace.php
It's hardcoded to "-- WordPress".
> Remove wp-admin title

- composer.json
- inc/namespace.php
> Add WP User Signups

- assets/admin-color-scheme.css
- inc/branding/namespace.php
Latest changes per https://github.com/humanmade/platform-dev/issues/321, also I took the defo user meta fix from hm-platform:beta
> Admin theme tweaks

- assets/admin-color-scheme.css
- inc/branding/namespace.php
Turns out I got the code wrong, because I never even know about this hex format!
> Fix colors for button hover

- inc/namespace.php
See https://github.com/humanmade/platform-cms/issues/43.
> Override maxupload size

- inc/branding/namespace.php
> Fix double slash in CSS URLs

- composer.json
We need to sync it now we have moves the WP dep to this package.
> Update cms-installer dep

- docs/themes.md
- inc/namespace.php
- load.php
> Allow setting default theme in config

- inc/namespace.php
Otherwise this has to wait for the first admin init, which causes an error on first load.
> Install sitemeta tables on install

- composer.json
> Update to WordPress 5.2.1

- inc/namespace.php
> Never show WP welcome panel

- inc/namespace.php
- inc/permalinks/namespace.php
- load.php
> Strip the default /blog prefix from permalinks

- inc/namespace.php
> Change login logo link

- inc/branding/namespace.php
- load.php
> Login Branding

- inc/branding/namespace.php
Fixes #60. We don't currently have a way to get the Altis version (https://github.com/humanmade/altis-core/pull/33 might add this), so currently the generator strings will look like `Altis (WordPress/5.2.1)` which I think is fine for now.
> Replace generator tags with Altis

- inc/namespace.php
- load.php
> 9: Remove emojis by default

- inc/branding/namespace.php
> Remove Howdy greeting

- assets/customize-settings.js
- inc/add_site_ui/namespace.php
- inc/branding/namespace.php
* Refactors the form handler into something more readable
* Adds validation for domains and paths (reserved paths now blocked, domains validated properly)
* Fixes up some JS problems
* Fixes issue with branding CSS
* Adds placeholders to indicate valid inputs
Built off #93.
> Improve and fix Add Site errors

- inc/namespace.php
This filter should return an array.
> Fix count first argument should be an array warning

- composer.json
> Update WP to 5.3

- inc/remove_updates/namespace.php
Performing these actions via the admin is not supported and must be done via CLI commands.
> Remove all update_* and upgrade_network caps

- inc/remove_updates/namespace.php
Uses `auto_update_core` filter
Fixes #123
> #123 Remove auto updates for core

- inc/block_editor/namespace.php
> Don't show shared blocks UI if user cant edit posts

- composer.json
> [Backport v2-branch-rc] Update WordPress to 5.3.1

- inc/add_site_ui/namespace.php
Fixes undefined variable notice when including the schema for a with custom domain.
Fixes #167
> Fixing undefined variable notice with custom domain

- composer.json
- docs/extended-cpts.md
- inc/namespace.php
> Adding extended custom post types library.

- inc/namespace.php
**NB** This PR is for comments part only of the main ticket #104
> Force comment pagination & limit to max 50

- composer.json
- docs/helper-functions.md
I run `composer run-script update-repo` and `composer run-script update-repo` on the main Altis project setup, but I didn't see the new package included in the `vendor/humanmade` directory.
Is what I did correct or am I missing something?
Fixes #81
> Add whitelist-html package as dependency

- inc/block_editor/namespace.php
Looks like a copy/pasta issue.
> Fixing the all items label for the Block Categories.

- docs/branding.md
- inc/branding/namespace.php
> Remove default user colour schemes

- assets/branding.css
- inc/branding/namespace.php
> Linking the Altis logo in the admin bar to the Dashboard.

- assets/branding.css
- inc/branding/namespace.php
> [Backport v2-branch] Use more specific class name, better theme compat #192

- assets/branding.css
- inc/branding/namespace.php
> [Backport v3-branch] Use more specific class name, better theme compat #192

- assets/branding.css
- inc/branding/namespace.php
> [Backport v1-branch] Fix logo styling and update version string #196

- assets/branding.css
- inc/branding/namespace.php
> [Backport v2-branch] Fix logo styling and update version string #196

- assets/branding.css
- inc/branding/namespace.php
> [Backport v3-branch] Fix logo styling and update version string #196

- docs/rss.md
- inc/namespace.php
- load.php
> Add option to disable RSS feeds

- inc/add_site_ui/namespace.php
> Rename add site screen's nonce to '_altis_add_site_nonce'

- inc/branding/namespace.php
> [Backport v3-branch] Output hidden input to avoid scheme reset

- composer.json
- docs/post-cloner.md
- inc/namespace.php
- load.php
@roborourke this depends on https://github.com/humanmade/post-cloner/pull/25 - so we'll probably have to bump the version as well?
> Add post cloner plugin

- assets/admin-color-scheme.css
- inc/branding/namespace.php
> WordPress 5.5 Updates

- composer.json
> Add Composer v2 support

- composer.json
Backport #268
Update CMS installer to 0.4.3
> [Backport v4-branch] Add Composer v2 support

- composer.json
Backport #268
Update CMS installer to 0.4.3
> [Backport v3-branch] Add Composer v2 support

- inc/namespace.php
> Fix: login-logo URL can be incorrect for all the sub-sites in a network

- inc/namespace.php
Backporting #301
---------------
Add check to redirect_canonical for equivalent query strings
This prevents unnecessary redirects where the query strings and base URLs are the same but formatted differently. This will prevent a bug with Batcache caching redirects to another URL with the same derived cache key and endlessly redirecting.
It is generally preferable to avoid unneeded redirects anyway so this is patching the WP core behaviour. There is a trac ticket describing the issue here https://core.trac.wordpress.org/ticket/41712
> [Backport v4-branch] Add check to redirect_canonical for equivalent query strings

- inc/namespace.php
> Fix remove emoji DNS prefetch warning

- inc/add_site_ui/namespace.php
> Add filter for the new site public default setting

- inc/add_site_ui/namespace.php
Backports #341 to v3 branch and resolves merge conflict.
> backport 341 to v3 branch

- composer.json
- docs/block-editor.md
- inc/block_editor/namespace.php
- inc/namespace.php
- load.php
> Add Altis Reusable Blocks

- composer.json
- docs/post-cloner.md
Related to https://github.com/humanmade/aws-analytics/issues/195
> Update Post Cloner to 1.3.0

- assets/admin-color-scheme.css
Adds global color CSS variables for Altis colors per the Altis brand guidelines.
related to work in humanmade/altis-seo#53 and humanmade/altis-seo#54
> Add altis css color variables

- assets/admin-color-scheme.css
- inc/add_site_ui/namespace.php
> Add guidance on custom domain DNS requirements

- tests/acceptance.suite.yml
- tests/acceptance/AuthorshipCest.php
- tests/acceptance/SignupsCest.php
- tests/acceptance/SitesCest.php
Fixes https://github.com/humanmade/product-dev/issues/834
Needs https://github.com/humanmade/altis-dev-tools-command/pull/18
> [tests] CMS module QA tests

- inc/namespace.php
Reverts humanmade/altis-cms#494
> Revert "Load plugins after initial install"

- docs/permalinks.md
Note that the filters in question are not limited to the main site, so we should add a check for is_multisite and is_main_site to make this usable for non-main-sites as well.
Related https://github.com/humanmade/altis-cms/issues/70
> Add a note on using blog prefix for permalinks

- tests/acceptance/AuthorshipCest.php
Trigger Elastic reindex command to reflect db changes.
Requires https://github.com/humanmade/altis-dev-tools/pull/311
Ref https://github.com/humanmade/altis-cms/issues/508
> Reindex content after DB changes

- inc/cli/namespace.php
There are a few expdcted instances off this, we use it for non blocking issues.
> Change install error reporting to ignore E_USER_WARNING

- .gitignore
- tests/acceptance/AuthorshipCest.php
> Fix Authorship tests

- composer.json
Bumps asset-loader to [latest version available on packagist.](https://packagist.org/packages/humanmade/asset-loader)
> Update humanmade/asset-loader to latest

- composer.json
See: https://github.com/humanmade/product-dev/issues/1215
> Update to WordPress 6.0.2

- composer.json
See: https://github.com/humanmade/product-dev/issues/1215
> Update to WordPress 5.9.4

- composer.json
See: https://github.com/humanmade/product-dev/issues/1215
> Update WordPress to 5.8.5

- inc/branding/namespace.php
> Accessibility update

- composer.json
- 15ed698 - Update to latest cms-installer version
> Update to latest cms-installer version

- composer.json
Reverts humanmade/altis-cms#681
> Revert "Update humanmade/asset-loader requirement from ^0.5.0 to ^0.6.3"

- composer.json
See https://github.com/humanmade/product-dev/issues/1534
> Upgrade to WordPress 6.5.0

- inc/namespace.php
Ref: https://github.com/humanmade/product-dev/issues/1521
> 1521 remove altis.cloud from dns prefetch

- composer.json
Updates WordPress to version 6.7.2
> Update to WordPress 6.7.2

- composer.json
Update the version of WordPress to 6.8.2
> Update to WordPress 6.8.2

- composer.json
> Update WordPress to 6.7.3
