humanmade/altis-cms

composer.json, inc/namespace.php, inc/remove_updates/namespace.php, load.php
This removes the update nags and cron checks for themes, plugins and core.
=> Remove updates from showing in the WordPress admin

wp-config.php
When using WP CLI I noticed that the content directory was set to `/wordpress/content`. Using `__DIR__` means it's correct for both the CLI and web server.
=> Use __DIR__ to ensure WP CLI gets correct path

inc/branding/namespace.php
This adds a default splash page to improve the new user experience. This splash page is only triggered when:
* The theme is set to the default
* The theme is missing
* You're on development or local environments
This is modelled off the default Symfony splash page:
We should further theme this with branding colours, but do this via the `wp_die()` handler rather than here.
=> Add default splash page

composer.json
Will mean we have less updates to do on cms-installer and we can control the WP version with less effort.
Updating to 5.2 at the same time. Question though, should we make this `~5.2.0` to reduce WP upgrading friction?
Related to https://github.com/humanmade/platform-cms-installer/pull/5
=> Add the WP installer to this package

inc/namespace.php
In https://github.com/humanmade/platform-cms-installer/pull/5 we bumped to WordPress 5.2.
We want to disable a couple of the features, specifically Site Health and the Fatal Handler. These are both features for non-technical users to understand the php errors and environment errors for their site. As we are targetting a much more technical audience of developers who will be expected to deal with these issues, these features are not aligned well with what we want to show in the admin.
The WP Recovery Mode as it happens is not enabled in Multisite, so we don't have to do anything there.
=> WordPress 5.2 Modifications

inc/block_editor/namespace.php
This taxonomy doesn't need to be set to public as other plugins use that to determine whether to extend the edit screen with client side features such as SEO meta fields.
=> Change block category taxonomy to private

assets/branding.css
Hide version/update button from At a Glance dashboard widget
Closes #86
=> 86: Hide WP version + update btn

inc/namespace.php
This was introduced in https://github.com/humanmade/altis-cms/pull/83/commits/457b5eaf8e016dda276ccf1fd4ba347b86ddb77b, but this function was never defined.
=> Remove nonexistant hook function

inc/remove_updates/namespace.php
This makes sure when there is a WP update available, it doesn't show on `wp-admin/network/update-core.php` or the admin bar.
=> Remove update_core capability

inc/namespace.php
Currently, the disable emoji feature (#9) is broken, as the `remove_action` calls happen before the `add_action` calls.
This should trigger a 2.0.1 release, as the feature is totally broken. The question is, should we change the default value so that there's no changes when deploying a minor change?
=> Move remove_emoji callback to plugins_loaded

inc/remove_updates/namespace.php
Under normal running conditions this shouldn't be hit due to auto-updates being disabled but is a safety fallback in case something changes in WP Core.
=> Remove maintenance nag from admin notices.

composer.json
This is to release a 2.1.0-rc1 release of the CMS module with WP 5.3
=> Update WP to 5.3

inc/namespace.php
We don't have clients using admin_email as we usually set up sites, so we don't want this behaviour. It also gets in the way on local development.
=> Disable the admin_email verfication check on login.

inc/block_editor/namespace.php
Fixes a fatal error in CLI runs, missed it as the running app was unaffected.
=> Ensure permission check doesnt happen in CLI / early run context

load.php
Other modules may rely on WP_INITIAL_INSTALL so lets make this the first to execute by default.
=> Bootstrap module early

composer.json
=> [Backport v2-branch-rc] Update johnpbloch/wordpress requirement from 5.3.1 to 5.3.2

inc/namespace.php, load.php
Allows `wp_is_large_network` to be controlled via default settings. Can be explicitly set to true or false, or null for WordPress default behaviour. Defaults to true.
See #99
=> #99 Set wp_is_large_network to true

assets/admin-color-scheme.css
Addresses the color scheme issues with the `box-shadow` on focused anchor elements, `border-left-color` on the active contextual help tab, and the `box-shadow` on the active sidebar panel tab.
Also see https://github.com/humanmade/altis-documentation/pull/110 for the remaining styles changes in the documentation repo.
Fixes #114
=> Fixing box-shadow and border-left-color to match design notes in #114

assets/branding.css, inc/branding/namespace.php
Sets the width of the Altis menu item in the menu bar in the admin only, and when the sidebar is not collapsed (folded). 
Frontend
Admin
Admin - sidebar collapsed
See #115
=> #115 Fix Altis spacing in the admin bar

assets/branding.js, inc/branding/namespace.php
Fixes: https://github.com/humanmade/platform-dev/issues/381
Uses pure CSS to animate the SVG instead of JS like the original ticket requested.
=> Replace WP preview animation with Altis animation

inc/namespace.php
Some plugins or code can register asset URLs with relative paths. This does work in the browser however the browser security plugin will throw an error.
We can fix the problem globally by doing this.
=> Normalise asset URLs to remove relative paths

assets/branding.css, inc/branding/namespace.php
Fixes some img alignment issues in themes that have global styles for images or use the `.icon` CSS class.
=> Use more specific class name, better theme compat

assets/branding.css, inc/branding/namespace.php
The older versions were kinda confused by the padding changing if the admin bar item was a link or not. I also forgot to update the CSS file version string.
=> Fix logo styling and update version string

wp-config.php
As an escape hatch for things that need to be loaded super early, let's add a load-early config file. (Documentation for this will be in the Docs module rather than here.)
=> Load .config/load-early.php as early as possible

wp-config.php
This is done in wp-config-production.php as well so I think it makes sense to ensure this behaviour is always consistent. Also allows us to deprecate wp-config-production.php in future now that there's nothing dynamically generated in there.
=> Check for table prefix set in ENV in main wp-config.php

composer.json
Turns out there was no packages published to packagist since 2017. This brings us up to the latest, which includes support for php 7.3+ (see https://github.com/humanmade/platform-dev/issues/511)
Changelog:
* PHP 7.3 support
* Rename text domain back to match WordPress.org plugin slug
* Database schema update
Specifically see https://github.com/stuttter/wp-user-signups/commit/ad77b22ee0b5b1156f114f0cab24cac5963ad1d1 on the schema switch. The upgrade routine should automatically be applied.
=> Upgrade wp-user-signups to 5.0.0

inc/namespace.php
WP 5.4 introduces a new dashboard widget with the site healthcheck, because we use custom healthchecks this is misleading for Altis so we need to remove it by default.
=> Hide healthcheck dashboard widget

assets/editor-settings.js, inc/block_editor/namespace.php
In WP 5.4 the block editor will by default open in full screen mode with the welcome guide showing.
This update sets both of those defaults to false and allows for persisting settings users have opted in to.
=> Change the WP 5.4 default block editor settings

assets/admin-color-scheme.css, inc/branding/namespace.php
There were quite a few places not covered by our Altis color scheme CSS. This patches the bulk of those cases. Notable additions:
- Styling for `wp-components` CSS, makes the Gutenberg editor colour scheme inline with the rest of the admin
- Styling for Query Monitor
- Styling audience estimate visualisations
Fixes #117
=> Altis styling for QM and Components

inc/branding/namespace.php
I forgot to do this in the previous PR updating the styles. We need to ensure the latest version is downloaded when this goes to production environments with a long cache time out.
=> Bump the admin theme CSS version

inc/branding/namespace.php
> By default, WordPress will send its own logo for favicon requests.
> favicon.ico is blocked by our Cloud servers, but local installs will
> incorrectly show the WordPress logo due to this fallback.
>
> This function replaces the fallback with a zero-byte icon file, which was
> the fallback prior to WordPress 5.4. (Sites can continue to use the site
> icon functionality to set their own icons instead.)
See https://make.wordpress.org/core/2020/02/19/enhancements-to-favicon-handling-in-wordpress-5-4/
We missed this during the 5.4 upgrade; I suspect local-server matches the Cloud behaviour?
=> Remove default WP favicon

.build-script
Fixes https://github.com/humanmade/altis-cms/issues/168
@joehoyle I'm not clear on how to test the second acceptance criteria. Do you mean run the command locally with that parameter? `composer create-project altis/skeleton altis-test --apcu-autoloader`
=> Add autoloader flag to command

inc/branding/namespace.php
Fixes #241.
Turns out that WordPress will default this back to `fresh` if there's no POST value: https://github.com/WordPress/wordpress-develop/blob/9bd4234bf6e39189fb76ee5161bdba38d087b251/src/wp-admin/includes/user.php#L131
=> Output hidden input to avoid scheme reset

composer.json, inc/namespace.php, inc/signup_notification/namespace.php
Removes the default `wpmu_signup_blog_notification` and replaces it with an Altis one, so that we can control the email address the notices are sent from. 
See https://github.com/humanmade/altis-cms/issues/238
=> Replace WP blog signup notification

composer.json, inc/namespace.php, inc/network_ui/namespace.php, load.php
The sites list has an unclear visual hierarchy, and highlights less relevant details for most users.
This PR changes the site list to have site names as the primary entry instead of the URL, and de-emphasises less-important information. Additionally, it hides the rarely-used Spam action primarily used for WordPress.com-style open-registration multisites.
Before | After
-- | --
Still needs docs for the additional setting.
=> Override sites list for better detail

.build-script
Deploys can still try and go ahead even if a build step fails. This will make sure that doesn't happen.
Fixes #262
=> Add set -e to build script

docs/helper-functions.md
Headings should start with `h1`.
Fixes #253
=> Fix headings in docs/helper-functions.md

inc/remove_updates/namespace.php
WordPress' automatic updater expects this constant to return true if auto updates are to be disabled:
https://github.com/WordPress/WordPress/blob/9da0a44b3e70117089257777cc38a3305a6c6c77/wp-admin/includes/class-wp-automatic-updater.php#L41
=> set AUTOMATIC_UPDATER_DISABLED to true to disable auto updates

inc/namespace.php
This prevents unnecessary redirects where the query strings and base URLs are the same but formatted differently. This will prevent a bug with Batcache caching redirects to another URL with the same derived cache key and endlessly redirecting.
It is generally preferable to avoid unneeded redirects anyway so this is patching the WP core behaviour. There is a trac ticket describing the issue here https://core.trac.wordpress.org/ticket/41712
Fixes #302
=> Add check to redirect_canonical for equivalent query strings

inc/namespace.php
In the network admin sites list there are links to perform certain actions like archive/deactivate/delete and so on. Because the referer header is not available in cloud environments the interstitial confirmation forms get an empty value for the `_wp_htt_referer` field resulting in an expired link error page on confirmation.
This adds the referer as a query string argument to any network admin URLs with the `confirm` action so that the referer can be read from there instead.
Fixes #295
=> Fix network admin confirm site action forms

inc/namespace.php
The action links in the user signups UI relied on the value `wp_get_referer()` during processing. As this is missing in cloud environments the logic would result in an endless redirect loop.
This passes the referer via the URL query string and allows it to function normally.
=> Fix user signups action link redirect loop

inc/add_site_ui/namespace.php
`sanitize_text_field` does a lot of important work that we want to use for urls. However, what it _doesn't_ do, is disallow text strings from having spaces, which is also important for URLs.
Additionally, there is no handling for IDNAs or other variations that should be allowed. This PR:
* adds URL sanitization that covers additional steps that weren't being handled previously when new sites were created (this code was based off [the old HappyTables code](https://github.com/humanmade/happytables/blob/master/content/plugins-mu/ht-domains/ht-domains.php#L88-L144) for the same)
* pulls in the `Requests_IDNAEncoder` class to properly encode IDNAs
* adds URL encoding for subdirectory sites, so those respect internationalized characters as well (e.g. `domain.com/納豆`)
fixes #303
=> Better sanitization and validation for subdomains, subdirectories and new site URLs

composer.json, docs/authorship.md, inc/namespace.php, load.php
Fixes #337
Add the plugin, the installer override, config option and docs based on the plugin's readme.
The feature itself doesn't require or need anything in the way of further integration so this is quite straightforward.
=> Add authorship plugin

composer.json, docs/post-cloner.md
Fixes the cloned post permalink issue and adds documentation for the `post_cloner_strip_cloned` filter.
=> Update post cloner to 1.4.0

inc/branding/namespace.php
This theme was added in WordPress 5.5 so needs backporting to Altis v5.
Fixes https://github.com/humanmade/product-dev/issues/680
=> Remove the modern admin theme

composer.json
Updates WordPress to the latest security patch.
https://wordpress.org/support/wordpress-version/version-5-6-4/
=> WordPress 5.6.4 update

composer.json
Updates WordPress to the latest security patch
- [Release Notes](https://wordpress.org/support/wordpress-version/version-5-5-5/)
=> Update WordPress to 5.5.5

inc/namespace.php
Even if the network is considered large from within the config, display pagination when listing the network users in network/users.php
A network defined as large would prevent this and while Altis defines all networks as large by default, this was an annoying issue in the network users list.
This can be considered as a new feature and not a bug as it's a hack to a WP feature happening because of an Altis configuration field.
=> Display user pagination in network/users.php

assets/branding.css, composer.json, docs/local-avatars.md, inc/namespace.php, load.php
Supersedes #111 
Fixes #7 
* Adds Simple Local Avatars to CMS module
* Adds `10up/simple-local-avatars` to the install overrides in the `composer.json`
* Adds a config option to enable/disable local avatars
* Hides the default Profile Picture field if local avatars is enabled
* Adds documentation about the config option and available filters.
=> add simple local avatars

docs/rss.md
Adds a link to the WordPress documentation page for RSS feeds. 
See #393.
=> #393 Add a link to WordPress RSS documentation

docs/local-avatars.md
This filter is operating on bytes, not kilobytes, so `2 * 1024` is 2KB, not 2MB.
=> FIx code comment in documentation for `simple_local_avatars_upload_limit` filter

inc/namespace.php
The signups plugin will try to create or upgrade its db tables on `admin_init` now. Loading these was throwing up errors during the installation process.
=> Load plugins after initial install

assets/admin-color-scheme.css
#359 When hovering over an admin toolbar menu item, the change in colour is barely noticeable. It changes from very light grey to white. ( Hovering over Media )
Changed the menu item color from that of the sidebar links to keep some consistency. ( Hovering over Media )
=> Increase the admin toolbar hover contrast.

inc/remove_updates/namespace.php
Saves some space in the admin bar for a link that is unsupported anyway.
Fixes #524
=> Remove updates admin bar menu item

inc/branding/namespace.php
This PR fixes the original issue reported in #482 where the below error shown when on the widgets page:
> wp_enqueue_script() was called incorrectly. "wp-editor" script should not be enqueued together with the new widgets editor (wp-edit-widgets or wp-customize-widgets). Please see Debugging in WordPress for more information. (This message was added in version 5.8.0.)
Steps to confirm:
1. Login to the site
2. View the widgets page
3. View query Monitor, you shouldn't see the error mentioned above that `wp_enqueue_script() was called incorrectly.`
=> Enqueued script warning for wp-editor on widgets screen

.build-script
Slack convo for reference: https://hmn.slack.com/archives/C03K3J34A/p1660143713204989
This can help to keep build sizes down by fetching software without superfluous files.
=> Add `--prefer-dist` to composer install command

inc/namespace.php
Fixes - https://github.com/humanmade/altis-cms/issues/641
=> Fix parse_str() deprecated notice in PHP 8.1

inc/branding/namespace.php
Fixes https://github.com/humanmade/altis-cms/issues/644
Remove tabindex as it is redundant, as links already get keyboard focus by nature.
=> Remove tabindex

wp-config.php
If there's a configuration problem and an expected constant is missing, the application still responds with a `200`. This changes that to a `500`.
=> Return an HTTP 500 response code when there's a configuration problem

assets/admin-color-scheme.css
Related issue - #657 
This PR resolves styling issues in Query Monitor's for Dark & Light appearance. 
1. Login to the wp-admin area.
2. Click on the Query Monitor tab so it shows at the bottom of the window.
3. Hover any of the tabs and observe the background color and text color are light making it harder to read.
4. Click on Altis Config and hover any of the modules and observer the background color and test color too are hard to read.
Light appearance - Hovering on a module in the Altis Config tab
Light appearance - Hovering on another module while the Altis Config tab is "active"
Dark appearance - Hovering on a module in the Altis Config tab
Dark appearance - Hovering on another module while the Altis Config tab is "active"
=> Change Query Monitor styling.

composer.json
Security update: https://wordpress.org/news/2022/10/wordpress-6-0-3-security-release/
=> Update to WordPress 5.9.5

composer.json
Security release: https://wordpress.org/news/2022/10/wordpress-6-0-3-security-release/
=> Update to WordPress 6.0.3

composer.json
Security release: https://wordpress.org/news/2022/10/wordpress-6-0-3-security-release/
=> Update to WordPress 5.8.6

composer.json
Updates the composer.json requirement to WordPress 6.1.1. Announcements and dev notes:
* https://wordpress.org/news/2022/11/misha/
* https://wordpress.org/news/2022/11/wordpress-6-1-1-maintenance-release/
* https://make.wordpress.org/core/tag/6-1/
=> Update to WordPress 6.1.1

lib/simple-local-avatars/includes/class-simple-local-avatars.php
There is a TypeError with PHP8 that's been fixed upstream and released in a newer version (with other changes) which we'll ship with v14. This PR backports the fix alone to v13.
See:
* https://github.com/10up/simple-local-avatars/pull/183
* https://github.com/10up/simple-local-avatars/commit/9f28dc352fae18a6fb9388c478bf7815c920b915
=> Fix a PHP8 TypeError in 10up/simple-local-avatars

docs/xmlrpc.md
Clarified the impact of disabling xml-rpc using composer.json, based on Altis Support conversations.
=> Explain distinction of blocking xml-rpc requests

composer.json
Updates `composer.json` to require WordPress 6.2.0
Addresses #706
=> Update WordPress to version 6.2..0

assets/admin-color-scheme.css
Some style overrides are in place for Query Monitor so that its styling more closely matches that of the purple Altis colour scheme in the admin area. However:
* The colours in these overrides are too stark (eg. dark purple for table row hover instead of pale blue)
* There are several bugs (eg. trailing icons on links aren't visible, links don't have hover states)
* The overrides aren't easily maintainable as QM evolves
These style overrides make it quite jarring to use the tool. I propose to remove all the style overrides for QM except for the Altis purple used in the main left hand side navigation menu.
Harshly contrasting table row hover state:
Barely visible trailing icon on links:
Correctly styled row hover state:
Correctly styled trailing icon on links:
Altis purple remains for the …
=> Reduce the style overrides for Query Monitor

composer.json
Maintenance and security release: https://wordpress.org/news/2023/05/wordpress-6-2-1-maintenance-security-release/
=> Update to WordPress 6.2.1

composer.json
Part of the 6.2.1 maintenance/security release: https://wordpress.org/news/2023/05/wordpress-6-2-1-maintenance-security-release/
=> Update to WordPress 6.1.2

composer.json
Part of the 6.2.1 maintenance/security release: https://wordpress.org/news/2023/05/wordpress-6-2-1-maintenance-security-release/
=> Update to WordPress 6.0.4

composer.json
Part of the 6.2.1 maintenance/security release: https://wordpress.org/news/2023/05/wordpress-6-2-1-maintenance-security-release/
=> Update to WordPress 5.9.6

composer.json
Ref: https://wordpress.org/news/2023/05/wordpress-6-2-2-security-release/
=> Update to WordPress 6.2.2

composer.json
Ref: https://wordpress.org/news/2023/05/wordpress-6-2-2-security-release/
=> Update to WordPress 6.1.3

composer.json
Ref: https://wordpress.org/news/2023/05/wordpress-6-2-2-security-release/
=> Update to WordPress 6.0.5

composer.json
Ref: https://wordpress.org/news/2023/05/wordpress-6-2-2-security-release/
=> Update to WordPress 5.9.7

composer.json
WordPress 6.3.1 Maintenance Release: https://wordpress.org/news/2023/08/wordpress-6-3-1-maintenance-release/
=> Update to WordPress 6.3.1

composer.json
Update johnpbloch/wordpress requirement from 6.0.5 to 6.0.6
=> Update johnpbloch/wordpress requirement from 6.0.5 to 6.0.6

composer.json
Upgrades WordPress to version 6.4.2
Fixes https://github.com/humanmade/altis-cms/issues/774
=> Update WordPress to 6.4.2

inc/signup_notification/namespace.php
There were some additional notification emails that were not filtered by `wp_mail_from`.
=> Add additional signup notification email overrides

composer.json
Updates core to 6.3.4 for Altis v17.
=> Update to WordPress 6.3.4

composer.json
Updates to core 6.2.5 for Altis v16.
=> Update to WordPress 6.2.5

composer.json
Update WordPress requirement from 6.5.2 to 6.5.3
=>  Update johnbloch/wordpress requirement from 6.5.2 to 6.5.3

inc/branding/namespace.php
Core 6.6 moved some priorities around for admin bar nodes. Our old priority can't find the my-account node because it's added at a later priority.
See: https://core.trac.wordpress.org/changeset/58759
=> Fix Howdy removal for WordPress 6.6

composer.json
Upgrade WordPress to version 6.7.0
Addresses https://github.com/humanmade/product-dev/issues/1619
=> Upgrade WordPress to 6.7.0

composer.json
Upgrades the WordPress package to 6.7.1
=> Upgrade to WordPress 6.7.1

docs/permalinks.md
The leading slash in the namespace is not necessary.
Hat tip: @stormrockwell
=> Remove leading slash from namespace in example
